export const SUBJECTS = [
  "Matematika",
  "Fizika",
  "Kimyo",
  "Biologiya",
  "Ingliz tili",
  "Rus tili",
  "Ona tili",
  "Adabiyot",
  "Tarix",
  "Geografiya",
  "Informatika",
  "Iqtisodiyot",
];

export const mockGroups = [
  {
    id: 1,
    name: "11-A",
    level: "11-sinf",
    studentsCount: 24,
    createdAt: "2025-09-01T08:00:00Z",
  },
  {
    id: 2,
    name: "11-B",
    level: "11-sinf",
    studentsCount: 22,
    createdAt: "2025-09-01T08:00:00Z",
  },
  {
    id: 3,
    name: "10-A",
    level: "10-sinf",
    studentsCount: 26,
    createdAt: "2025-09-02T08:00:00Z",
  },
  {
    id: 4,
    name: "10-B",
    level: "10-sinf",
    studentsCount: 25,
    createdAt: "2025-09-02T08:00:00Z",
  },
  {
    id: 5,
    name: "9-A",
    level: "9-sinf",
    studentsCount: 28,
    createdAt: "2025-09-03T08:00:00Z",
  },
  {
    id: 6,
    name: "9-B",
    level: "9-sinf",
    studentsCount: 27,
    createdAt: "2025-09-03T08:00:00Z",
  },
  {
    id: 7,
    name: "Informatika Guruh-1",
    level: "Maxsus",
    studentsCount: 15,
    createdAt: "2025-10-01T08:00:00Z",
  },
  {
    id: 8,
    name: "Informatika Guruh-2",
    level: "Maxsus",
    studentsCount: 18,
    createdAt: "2025-10-01T08:00:00Z",
  },
];

export const mockTeachers = [
  {
    id: 1,
    fullName: "Nargiza Saidova",
    username: "n.saidova",
    email: "saidova@edutest.uz",
    phone: "+998 90 123 45 67",
    subject: "Matematika",
    groups: [1, 2, 3],
    studentsCount: 72,
    semestersCount: 4,
    status: "active",
    createdAt: "2025-09-15T10:30:00Z",
  },
  {
    id: 2,
    fullName: "Oybek Rahimov",
    username: "o.rahimov",
    email: "rahimov@edutest.uz",
    phone: "+998 91 234 56 78",
    subject: "Fizika",
    groups: [1, 3, 5],
    studentsCount: 78,
    semestersCount: 3,
    status: "active",
    createdAt: "2025-09-18T14:20:00Z",
  },
  {
    id: 3,
    fullName: "Malika Yusupova",
    username: "m.yusupova",
    email: "yusupova@edutest.uz",
    phone: "+998 93 345 67 89",
    subject: "Ingliz tili",
    groups: [2, 4, 6],
    studentsCount: 74,
    semestersCount: 5,
    status: "active",
    createdAt: "2025-09-20T09:15:00Z",
  },
  {
    id: 4,
    fullName: "Sardor Komilov",
    username: "s.komilov",
    email: "komilov@edutest.uz",
    phone: "+998 94 456 78 90",
    subject: "Informatika",
    groups: [7, 8],
    studentsCount: 33,
    semestersCount: 6,
    status: "active",
    createdAt: "2025-10-01T11:00:00Z",
  },
  {
    id: 5,
    fullName: "Dilnoza Islamova",
    username: "d.islamova",
    email: "islamova@edutest.uz",
    phone: "+998 95 567 89 01",
    subject: "Kimyo",
    groups: [3, 4, 5],
    studentsCount: 79,
    semestersCount: 2,
    status: "inactive",
    createdAt: "2025-10-05T13:45:00Z",
  },
  {
    id: 6,
    fullName: "Jasur Abdullayev",
    username: "j.abdullayev",
    email: "abdullayev@edutest.uz",
    phone: "+998 97 678 90 12",
    subject: "Tarix",
    groups: [1, 2],
    studentsCount: 46,
    semestersCount: 3,
    status: "active",
    createdAt: "2025-10-10T16:20:00Z",
  },
];

const names = [
  "Aziz Karimov",
  "Malika Tursunova",
  "Bekzod Alimov",
  "Zarina Usmonova",
  "Javohir Yoqubov",
  "Nigora Xalilova",
  "Sanjar Ismoilov",
  "Gulnora Rahmonova",
  "Otabek Sharipov",
  "Feruza Akbarova",
  "Ruslan Xojiyev",
  "Kamola Ergasheva",
  "Akmal Nazarov",
  "Shahnoza Qosimova",
  "Temur Abdurahmonov",
  "Madina Olimova",
  "Farrux Mirzayev",
  "Sevara Ahmedova",
  "Doston Yusupov",
  "Lola Rustamova",
];
const seed = (i) => Math.abs((Math.sin(i * 999) * 10000) % 1);

export const mockStudents = names.map((name, idx) => ({
  id: idx + 1,
  fullName: name,
  username: name.toLowerCase().replace(/\s+/g, "."),
  email: `${name.toLowerCase().replace(/\s+/g, ".")}@student.uz`,
  groupId: (idx % 8) + 1,
  teacherId: (idx % 6) + 1,
  testsCompleted: Math.floor(seed(idx + 1) * 20) + 5,
  averageScore: Math.floor(seed(idx + 7) * 35) + 60,
  status: idx % 11 === 0 ? "inactive" : "active",
  createdAt: new Date(Date.now() - idx * 86400000 * 3).toISOString(),
}));

export const mockSemesters = [
  {
    id: 1,
    name: "Algebra asoslari",
    subject: "Matematika",
    teacherId: 1,
    groupId: 1,
    questionCount: 20,
    attempts: 2,
    deadline: "2026-05-15T23:59:00Z",
    status: "active",
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: 2,
    name: "Mexanika",
    subject: "Fizika",
    teacherId: 2,
    groupId: 3,
    questionCount: 25,
    attempts: 1,
    deadline: "2026-05-20T23:59:00Z",
    status: "active",
    createdAt: "2026-04-05T08:00:00Z",
  },
  {
    id: 3,
    name: "Grammar Tenses",
    subject: "Ingliz tili",
    teacherId: 3,
    groupId: 2,
    questionCount: 30,
    attempts: 3,
    deadline: "2026-04-10T23:59:00Z",
    status: "completed",
    createdAt: "2026-03-20T08:00:00Z",
  },
  {
    id: 4,
    name: "Python asoslari",
    subject: "Informatika",
    teacherId: 4,
    groupId: 7,
    questionCount: 15,
    attempts: 2,
    deadline: "2026-06-01T23:59:00Z",
    status: "active",
    createdAt: "2026-04-10T08:00:00Z",
  },
  {
    id: 5,
    name: "Organik kimyo",
    subject: "Kimyo",
    teacherId: 5,
    groupId: 4,
    questionCount: 22,
    attempts: 2,
    deadline: "2026-04-20T23:59:00Z",
    status: "active",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: 6,
    name: "Ikkinchi jahon urushi",
    subject: "Tarix",
    teacherId: 6,
    groupId: 2,
    questionCount: 18,
    attempts: 1,
    deadline: "2026-05-30T23:59:00Z",
    status: "active",
    createdAt: "2026-04-12T08:00:00Z",
  },
];

export const mockStats = {
  teachers: 6,
  students: 248,
  groups: 8,
  activeSemesters: 18,
  testsCompleted: 1247,
  averageScore: 78.4,
  teachersChange: 12.5,
  studentsChange: 8.2,
  semestersChange: 15.3,
  scoreChange: 3.1,
};

export const mockChartData = [
  { month: "May", tests: 145, students: 180 },
  { month: "Iyn", tests: 189, students: 195 },
  { month: "Iyl", tests: 156, students: 200 },
  { month: "Avg", tests: 98, students: 210 },
  { month: "Sen", tests: 267, students: 225 },
  { month: "Okt", tests: 312, students: 235 },
  { month: "Noy", tests: 289, students: 240 },
  { month: "Dek", tests: 345, students: 248 },
];

export const mockWeekly = [
  { day: "Dush", tests: 48 },
  { day: "Sesh", tests: 62 },
  { day: "Chor", tests: 55 },
  { day: "Pay", tests: 71 },
  { day: "Jum", tests: 85 },
  { day: "Shan", tests: 42 },
  { day: "Yak", tests: 28 },
];

export const mockRecentActivity = [
  {
    id: 1,
    type: "teacher_created",
    title: "Yangi o'qituvchi qo'shildi",
    description: "Jasur Abdullayev — Tarix",
    user: "Admin",
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 2,
    type: "semester_created",
    title: "Semestr boshlandi",
    description: "Algebra asoslari — 11-A",
    user: "Nargiza Saidova",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 3,
    type: "test_completed",
    title: "Test yakunlandi",
    description: "24 o'quvchi testni topshirdi",
    user: "Malika Yusupova",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 4,
    type: "student_joined",
    title: "12 yangi o'quvchi qo'shildi",
    description: "Informatika Guruh-2",
    user: "Sardor Komilov",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 5,
    type: "semester_completed",
    title: "Semestr tugatildi",
    description: "Fizika asoslari — 10-B",
    user: "Oybek Rahimov",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 6,
    type: "teacher_created",
    title: "Yangi o'qituvchi qo'shildi",
    description: "Dilnoza Islamova — Kimyo",
    user: "Admin",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
];

// ========== TEACHER-SPECIFIC MOCK DATA ==========

export const mockTeacherStats = {
  myGroups: 3,
  myStudents: 72,
  activeSemesters: 4,
  completedTests: 289,
  averageScore: 82.4,
  aiGenerated: 12,
  groupsChange: 0,
  studentsChange: 5.2,
  semestersChange: 25.0,
  scoreChange: 2.8,
};

export const mockTeacherChart = [
  { month: "May", submissions: 28, avgScore: 76 },
  { month: "Iyn", submissions: 42, avgScore: 78 },
  { month: "Iyl", submissions: 31, avgScore: 74 },
  { month: "Avg", submissions: 18, avgScore: 72 },
  { month: "Sen", submissions: 58, avgScore: 81 },
  { month: "Okt", submissions: 71, avgScore: 84 },
  { month: "Noy", submissions: 65, avgScore: 82 },
  { month: "Dek", submissions: 82, avgScore: 85 },
];

// O'qituvchi semestrlari (teacherId: 1 — Nargiza Saidova)
export const mockTeacherSemesters = [
  {
    id: 1,
    name: "Algebra asoslari",
    subject: "Matematika",
    teacherId: 1,
    groupId: 1,
    description: "Kvadrat tenglamalar, ko'phadlar va ularning ildizlari",
    questionCount: 20,
    attempts: 2,
    duration: 60,
    deadline: "2026-05-15T23:59:00Z",
    status: "active",
    autoGrade: true,
    sourceFile: "algebra-11sinf.pdf",
    aiPrompt:
      "11-sinf algebra darsligidan kvadrat tenglamalar mavzusida test yarating",
    submitted: 18,
    total: 24,
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: 2,
    name: "Trigonometriya",
    subject: "Matematika",
    teacherId: 1,
    groupId: 2,
    description: "Sinus, kosinus, tangens va ularning xossalari",
    questionCount: 25,
    attempts: 1,
    duration: 90,
    deadline: "2026-05-20T23:59:00Z",
    status: "active",
    autoGrade: true,
    sourceFile: "trigonometry.pdf",
    aiPrompt: "Trigonometriya bo'yicha asosiy formulalar va identifikatsiyalar",
    submitted: 14,
    total: 22,
    createdAt: "2026-04-05T08:00:00Z",
  },
  {
    id: 3,
    name: "Geometriya asoslari",
    subject: "Matematika",
    teacherId: 1,
    groupId: 3,
    description: "Planimetriya va uning teoremalari",
    questionCount: 18,
    attempts: 3,
    duration: 45,
    deadline: "2026-04-10T23:59:00Z",
    status: "completed",
    autoGrade: true,
    sourceFile: "geometry.docx",
    aiPrompt: "10-sinf geometriya darsligidan uchburchaklar mavzusi",
    submitted: 26,
    total: 26,
    createdAt: "2026-03-15T08:00:00Z",
  },
  {
    id: 4,
    name: "Darajalar va ildizlar",
    subject: "Matematika",
    teacherId: 1,
    groupId: 1,
    description: "Darajalar va ildizlar ustida amallar",
    questionCount: 15,
    attempts: 2,
    duration: 40,
    deadline: "2026-04-25T23:59:00Z",
    status: "draft",
    autoGrade: false,
    sourceFile: null,
    aiPrompt: "",
    submitted: 0,
    total: 24,
    createdAt: "2026-04-15T08:00:00Z",
  },
];

// Natijalar (har bir o'quvchining har bir semestrdagi natijasi)
export const mockResults = [
  {
    id: 1,
    studentId: 1,
    semesterId: 1,
    score: 92,
    attempts: 1,
    duration: 42,
    submittedAt: "2026-04-18T14:20:00Z",
    status: "completed",
  },
  {
    id: 2,
    studentId: 2,
    semesterId: 1,
    score: 78,
    attempts: 2,
    duration: 55,
    submittedAt: "2026-04-18T15:10:00Z",
    status: "completed",
  },
  {
    id: 3,
    studentId: 3,
    semesterId: 1,
    score: 85,
    attempts: 1,
    duration: 48,
    submittedAt: "2026-04-19T10:30:00Z",
    status: "completed",
  },
  {
    id: 4,
    studentId: 4,
    semesterId: 1,
    score: 64,
    attempts: 2,
    duration: 58,
    submittedAt: "2026-04-19T11:00:00Z",
    status: "completed",
  },
  {
    id: 5,
    studentId: 5,
    semesterId: 1,
    score: 95,
    attempts: 1,
    duration: 38,
    submittedAt: "2026-04-20T09:15:00Z",
    status: "completed",
  },
  {
    id: 6,
    studentId: 6,
    semesterId: 1,
    score: 70,
    attempts: 1,
    duration: 52,
    submittedAt: "2026-04-20T13:45:00Z",
    status: "completed",
  },
  {
    id: 7,
    studentId: 7,
    semesterId: 1,
    score: 88,
    attempts: 1,
    duration: 45,
    submittedAt: "2026-04-21T10:20:00Z",
    status: "completed",
  },
  {
    id: 8,
    studentId: 8,
    semesterId: 2,
    score: 82,
    attempts: 1,
    duration: 75,
    submittedAt: "2026-04-22T14:00:00Z",
    status: "completed",
  },
  {
    id: 9,
    studentId: 9,
    semesterId: 2,
    score: 91,
    attempts: 1,
    duration: 68,
    submittedAt: "2026-04-22T14:30:00Z",
    status: "completed",
  },
  {
    id: 10,
    studentId: 10,
    semesterId: 2,
    score: 76,
    attempts: 1,
    duration: 85,
    submittedAt: "2026-04-22T15:00:00Z",
    status: "completed",
  },
  {
    id: 11,
    studentId: 1,
    semesterId: 3,
    score: 94,
    attempts: 1,
    duration: 32,
    submittedAt: "2026-04-09T11:00:00Z",
    status: "completed",
  },
  {
    id: 12,
    studentId: 2,
    semesterId: 3,
    score: 87,
    attempts: 2,
    duration: 42,
    submittedAt: "2026-04-09T13:30:00Z",
    status: "completed",
  },
  {
    id: 13,
    studentId: 3,
    semesterId: 3,
    score: 73,
    attempts: 3,
    duration: 44,
    submittedAt: "2026-04-10T09:00:00Z",
    status: "completed",
  },
];

export const mockTeacherActivity = [
  {
    id: 1,
    type: "test_submitted",
    title: "Yangi test topshirildi",
    description: "Aziz Karimov — Algebra asoslari (92 ball)",
    timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 2,
    type: "ai_generated",
    title: "AI test yaratildi",
    description: "Trigonometriya — 25 savol",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 3,
    type: "semester_created",
    title: "Yangi semestr yaratildi",
    description: "Geometriya asoslari — 10-A",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 4,
    type: "test_submitted",
    title: "Test topshirildi",
    description: "Malika Tursunova — Mexanika (85 ball)",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 5,
    type: "deadline_warning",
    title: "Deadline yaqin",
    description: "Algebra asoslari — 3 kun qoldi",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];
// ========== STUDENT-SPECIFIC MOCK DATA ==========

export const mockStudentStats = {
  totalTests: 12,
  completed: 9,
  pending: 3,
  averageScore: 84,
};

// So'nggi oylardagi ball dinamikasi
export const mockStudentProgress = [
  { month: "Sen", score: 72 },
  { month: "Okt", score: 78 },
  { month: "Noy", score: 85 },
  { month: "Dek", score: 81 },
  { month: "Yan", score: 88 },
  { month: "Fev", score: 92 },
];

// Student'ning testlari — barchasi (active/completed/draft holatida)
export const mockStudentSemesters = [
  {
    id: 1, name: "Algebra asoslari", subject: "Matematika", teacher: "Nargiza Saidova",
    description: "Kvadrat tenglamalar va ko'phadlar",
    questionCount: 20, attempts: 2, duration: 60,
    deadline: "2026-05-15T23:59:00Z", status: "active",
    attemptsUsed: 0, bestScore: null, autoGrade: true,
  },
  {
    id: 2, name: "Trigonometriya", subject: "Matematika", teacher: "Nargiza Saidova",
    description: "Sinus, kosinus va tangens",
    questionCount: 25, attempts: 1, duration: 90,
    deadline: "2026-05-20T23:59:00Z", status: "active",
    attemptsUsed: 0, bestScore: null, autoGrade: true,
  },
  {
    id: 3, name: "Mexanika", subject: "Fizika", teacher: "Oybek Rahimov",
    description: "Nyuton qonunlari va harakat",
    questionCount: 15, attempts: 2, duration: 45,
    deadline: "2026-04-28T23:59:00Z", status: "active",
    attemptsUsed: 1, bestScore: 78, autoGrade: true,
  },
  {
    id: 4, name: "Grammar Tenses", subject: "Ingliz tili", teacher: "Malika Yusupova",
    description: "Past, Present, Future Tenses",
    questionCount: 30, attempts: 3, duration: 50,
    deadline: "2026-05-10T23:59:00Z", status: "active",
    attemptsUsed: 2, bestScore: 85, autoGrade: true,
  },
  {
    id: 5, name: "Geometriya asoslari", subject: "Matematika", teacher: "Nargiza Saidova",
    description: "Planimetriya",
    questionCount: 18, attempts: 3, duration: 45,
    deadline: "2026-04-10T23:59:00Z", status: "completed",
    attemptsUsed: 3, bestScore: 94, autoGrade: true,
  },
  {
    id: 6, name: "Organik kimyo", subject: "Kimyo", teacher: "Dilnoza Islamova",
    description: "Uglevodorodlar",
    questionCount: 22, attempts: 2, duration: 60,
    deadline: "2026-04-20T23:59:00Z", status: "active",
    attemptsUsed: 1, bestScore: 72, autoGrade: true,
  },
];

// Student'ning natijalari (topshirilgan testlar)
export const mockStudentResults = [
  {
    id: 1, semesterId: 5, semesterName: "Geometriya asoslari", subject: "Matematika", teacher: "Nargiza Saidova",
    score: 94, correct: 17, total: 18, duration: 32, attemptNumber: 1,
    submittedAt: "2026-04-09T11:00:00Z",
  },
  {
    id: 2, semesterId: 4, semesterName: "Grammar Tenses", subject: "Ingliz tili", teacher: "Malika Yusupova",
    score: 85, correct: 25, total: 30, duration: 42, attemptNumber: 2,
    submittedAt: "2026-04-15T13:30:00Z",
  },
  {
    id: 3, semesterId: 3, semesterName: "Mexanika", subject: "Fizika", teacher: "Oybek Rahimov",
    score: 78, correct: 11, total: 15, duration: 38, attemptNumber: 1,
    submittedAt: "2026-04-20T15:00:00Z",
  },
  {
    id: 4, semesterId: 6, semesterName: "Organik kimyo", subject: "Kimyo", teacher: "Dilnoza Islamova",
    score: 72, correct: 16, total: 22, duration: 52, attemptNumber: 1,
    submittedAt: "2026-04-18T10:20:00Z",
  },
  {
    id: 5, semesterId: 5, semesterName: "Geometriya asoslari", subject: "Matematika", teacher: "Nargiza Saidova",
    score: 88, correct: 16, total: 18, duration: 36, attemptNumber: 2,
    submittedAt: "2026-04-03T14:00:00Z",
  },
  {
    id: 6, semesterId: 4, semesterName: "Grammar Tenses", subject: "Ingliz tili", teacher: "Malika Yusupova",
    score: 68, correct: 20, total: 30, duration: 48, attemptNumber: 1,
    submittedAt: "2026-04-01T09:30:00Z",
  },
  {
    id: 7, semesterId: 5, semesterName: "Geometriya asoslari", subject: "Matematika", teacher: "Nargiza Saidova",
    score: 76, correct: 14, total: 18, duration: 40, attemptNumber: 3,
    submittedAt: "2026-03-28T16:15:00Z",
  },
];

// Demo test savollari (student test topshirganda ko'rinadi)
export const mockTestQuestions = [
  {
    id: 1,
    text: "Kvadrat tenglama x² - 5x + 6 = 0 ning ildizlari qaysi?",
    options: [
      { id: "a", text: "x₁ = 2, x₂ = 3" },
      { id: "b", text: "x₁ = 1, x₂ = 6" },
      { id: "c", text: "x₁ = -2, x₂ = -3" },
      { id: "d", text: "x₁ = 5, x₂ = 6" },
    ],
    correctOption: "a",
    explanation: "Vyeta teoremasi bo'yicha: x₁ + x₂ = 5, x₁ · x₂ = 6 → x₁=2, x₂=3",
  },
  {
    id: 2,
    text: "(x + 3)² ni yoyib yozing.",
    options: [
      { id: "a", text: "x² + 6x + 9" },
      { id: "b", text: "x² + 9" },
      { id: "c", text: "x² + 3x + 9" },
      { id: "d", text: "x² + 6x + 6" },
    ],
    correctOption: "a",
    explanation: "(a + b)² = a² + 2ab + b² formulasi bo'yicha: (x)² + 2·x·3 + 3² = x² + 6x + 9",
  },
  {
    id: 3,
    text: "Agar f(x) = 2x + 3 bo'lsa, f(5) nimaga teng?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "11" },
      { id: "c", text: "13" },
      { id: "d", text: "8" },
    ],
    correctOption: "c",
    explanation: "f(5) = 2·5 + 3 = 10 + 3 = 13",
  },
  {
    id: 4,
    text: "Diskriminant nima?",
    options: [
      { id: "a", text: "b² - 4ac" },
      { id: "b", text: "b² + 4ac" },
      { id: "c", text: "2a" },
      { id: "d", text: "a² - 4bc" },
    ],
    correctOption: "a",
    explanation: "Kvadrat tenglamaning diskriminanti D = b² - 4ac formulasi bilan topiladi.",
  },
  {
    id: 5,
    text: "log₁₀(100) ning qiymati qanday?",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "2" },
      { id: "c", text: "10" },
      { id: "d", text: "100" },
    ],
    correctOption: "b",
    explanation: "10² = 100, shuning uchun log₁₀(100) = 2",
  },
  {
    id: 6,
    text: "Qaysi son irratsional?",
    options: [
      { id: "a", text: "0.5" },
      { id: "b", text: "√2" },
      { id: "c", text: "3/4" },
      { id: "d", text: "-5" },
    ],
    correctOption: "b",
    explanation: "√2 = 1.41421356... cheksiz va davriy bo'lmagan son — irratsional.",
  },
  {
    id: 7,
    text: "Agar a = 3, b = 4 bo'lsa, a² + b² nimaga teng?",
    options: [
      { id: "a", text: "14" },
      { id: "b", text: "25" },
      { id: "c", text: "49" },
      { id: "d", text: "7" },
    ],
    correctOption: "b",
    explanation: "a² + b² = 3² + 4² = 9 + 16 = 25",
  },
  {
    id: 8,
    text: "Sin(90°) nimaga teng?",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "0.5" },
      { id: "c", text: "1" },
      { id: "d", text: "√2/2" },
    ],
    correctOption: "c",
    explanation: "Sin(90°) = 1 (trigonometrik aylanadagi maksimal qiymat)",
  },
  {
    id: 9,
    text: "2x + 5 = 15 tenglamaning yechimi qaysi?",
    options: [
      { id: "a", text: "x = 3" },
      { id: "b", text: "x = 5" },
      { id: "c", text: "x = 10" },
      { id: "d", text: "x = 7.5" },
    ],
    correctOption: "b",
    explanation: "2x = 15 - 5 = 10, demak x = 5",
  },
  {
    id: 10,
    text: "Uchburchakning ichki burchaklari yig'indisi necha darajaga teng?",
    options: [
      { id: "a", text: "90°" },
      { id: "b", text: "180°" },
      { id: "c", text: "270°" },
      { id: "d", text: "360°" },
    ],
    correctOption: "b",
    explanation: "Istalgan uchburchakning ichki burchaklari yig'indisi 180° ga teng.",
  },
];
// Alias — ba'zi eski komponentlar mockActivity deb import qilishi mumkin
export const mockActivity = mockRecentActivity;
